### ISSUE TITLE
Incompatibility with betterhud [total-glitchout of appp]

### ISSUE THREAD

**Issue by HaaDT** [Cheos137/ArmorpointsPlusplus#13]
Description:
I was modifying the hud to make it more like an RPG, and well I added Armor Points ++ / Health Stacking version v2.0.1 [1.12.2] to add the armor support I wanted from
AttributeFix, so I combined the RPG-Hud so I can move more in the hud, and I've already removed the mod and everything and the problem is Armor Points ++ / Health Stacking, if the player is without armor the mod leaves the interface of game in case the textures are all white and buggy, but if you are with any armor the problem is solved as in the image, I also left a photo with the mods I was using to make the hud, but I'm sure it's the RPG-hud still

To Reproduce:
1-add Armor Points ++ / Health Stack version v2.0.1 [1.12.2]
2-and also put the RPG-Hud together and The Better Hud mod
3-normally ready the bug that happens, if it doesn't happen and just change the HUD type in RPG-hud options

Expected behavior:
that the two modes merge seamlessly in the game's hud

Version:
v2.0.1 [1.12.2]

Screenshots:
![2021-10-14_21 26 51](https://user-images.githubusercontent.com/55682433/137418123-21c1bb2f-976f-4aac-b7d7-1b2633315887.png)
![2021-10-14_21 32 30](https://user-images.githubusercontent.com/55682433/137418126-31cd24dc-59b0-462b-9b2f-6eba42473925.png)

![image](https://user-images.githubusercontent.com/55682433/137418198-5b8144cd-b3fc-4039-9e66-540544b02021.png)

**Comment by HaaDT** [comment]
Correction:
I did more testing and the bug itself does not occur by the RPG-Hud but by the BetterHud mod

**Comment by HaaDT** [comment]
one so it will be in the same mode as the armor bar, I thought the idea would be the two bars all together, since this is a very big charm of the mod, the two being together, but having this option is very good too, good luck hey, I hope I helped

**Comment by HaaDT** [comment]
I have an idea, there in the photo there is a bar that you move and change the names, this could also be used in this toughness bar, it would have 3 modes, the first would be off, the second the compact mode, the third the separate one, and also as possibly the toughness bar can have a color change depending on how much you have, it would be interesting a way to see how much of it you have in equal numbers and done in the armor bar, it can even be together with the armor or separate when the option is set to separate the two bars

![image](https://user-images.githubusercontent.com/55682433/137544623-e46dbe3f-9572-4e35-8cd7-9629565fcab0.png)

**Comment by HaaDT** [comment]
in 1.16 has changed a lot in the programming of forge and its methods, but maybe it's something of changes or something similar

**Comment by HaaDT** [comment]
another idea then would be to divide the configurations into category like you did, but now like one for armors both and one for heart, I think the easiest way to make it more organized is to divide more

**Comment by Cheos137** [comment]
thank you :D

**Comment by HaaDT** [comment]
I was looking here, have you ever thought about doing something for the hunger bar? at least add her that number on the side that counts or something, she's abandoned kkkkk

**Comment by Cheos137** [comment]
A number next to the hunger bar is something i could do... but i'd do nothing more than that, because otherwise it would render AppleSkin useless (and i don't want that as i kinda fancy that mod)

**Comment by HaaDT** [comment]
it's true that mod is very good, but it's just an idea kkk but maybe it's nice to have a number on the side that you activate optional to make the mod more complete

**Comment by HaaDT** [comment]
more and just my taste no biggie

**Comment by HaaDT** [comment]
another idea would also be to make the system in case the hud of the bar is changed according to a user's color school, like using hex colors like this, the person chooses the color it applies to the bar and changes it to the desired color for each level by the user, it's a good idea but it should work the handle as you would have to change the entire code

**Comment by HaaDT** [comment]
Also, it would be great to add a shadow below the numbers on the hud, because there are times when you can't see the number, like you're in the snow and you can't see anything if it's all white, so an umbrella underneath is the same what's in vanila would be interesting

**Comment by Cheos137** [comment]
the appp glitches when used together with betterhud are resolved in 3.0.0 (1.12 alpha build yet to release)
all remaining issues are not appp's but betterhuds fault
