### ISSUE TITLE
[Bug]: No setting to change how many icons get shown for a toughness of 1

### ISSUE THREAD

**Issue by Nyphet** [Cheos137/ArmorpointsPlusplus#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I wanted to make so that Minecraft Vanilla armors would show only up to 10 armor toughness points, whereas with default settings the full netherite set shows 13 points, making the second orange overlayed bar appear, which is what I want to avoid.
In the webpage is says "Note: How many icons get shown for a toughness of 1 can be set in the config." however I was not able to find such option anywhere in the settings.
This leaves me with the only option of disabling armor toughness, which is really a shame because it make diamond and netherite sets indistinguishable.

### Version

BETA 3.0.0 for Minecraft Forge 1.18.1

### To Reproduce

Just install the mod and search for the config.

### Expexted Behavior

I expected to find a setting, like for absorption, resistance and protection, to change how many toughness icons are shown for a certain amount of toughness points.

### Screenshots

![image](https://user-images.githubusercontent.com/65339023/160486371-56576319-ff82-422d-9c9b-f85cc052af72.png)
![image](https://user-images.githubusercontent.com/65339023/160489407-0a5dcb32-b2a7-4cb9-bf12-89be34e1b8c8.png)

**Comment by Cheos137** [comment]
In 3.0.0 alpha this setting was removed as i deemed it irrelevant, but i can add it back - thus marking this as a feature request.
Also, the website is not up to date for v3.0.0 beta, but still shows all features of v2.1.x

**Comment by Nyphet** [comment]
Yes, if you could add it back it would be awesome for me, for the reasons stated above.
Thank you

**Comment by Cheos137** [comment]
re-added in dae4142 (aka beta5)
