### ISSUE TITLE
Crash in modpack

### ISSUE THREAD

**Issue by Rad233** [Cheos137/ArmorpointsPlusplus#26]
### Description

I added this mod in my modpack, and the game crashed when I switched to survival mode. Below is the crash report and the log file.
I could't make sure whether it's a bug or it's the incompatibility with other mods(Maybe the Victus mod?), so I didn't open the issue as a bug.

### Other Files

[crash-2022-05-03_01.07.57-client.txt](https://github.com/Cheos137/ArmorpointsPlusplus/files/8604868/crash-2022-05-03_01.07.57-client.txt)
[latest.log](https://github.com/Cheos137/ArmorpointsPlusplus/files/8604869/latest.log)

**Comment by Cheos137** [comment]
There was some update in obfuscated names from 1.18.1 to 1.18.2 which fabric didn't handle well (forge handled it without any problems)
- the v3.0.0 does only support 1.18.2, though there was a beta version targeting 1.18.1 (doesn't have the full range of features, though)... i've uploaded that one to my webserver for you to use: https://files.cheos.dev/armorpointspp-fabric-1.18.1-3.0.0-beta3.jar
