### ISSUE TITLE
[Bug]: Glitched GUI.

### ISSUE THREAD

**Issue by Xano052** [Cheos137/ArmorpointsPlusplus#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With i think its journey map, it glitches EVERYTHING OUT, other than version 2. Please fix this its making it harder to use the mod. Thank you!
I had the following mods added to my modpack, 
AP++, AppleSkin, Armor Status HUD Renewed, BobLib, Hwyla, JourneyMap, Lock on, My Hero Academia, and Neat.
I added JEI to these mods and all of a sudden things were glitched. 
I then deleted the AP++ mod and it was fixed, just the AP++ mod as well was deleted and it was working.

### Version

3.0.1 for Minecraft Forge 1.16.5

### Version

forge - 1.16.5

### To Reproduce

Download these mods for 1.16.5 Minecraft Forge
AP++, AppleSkin, Armor Status HUD Renewed, BobLib, Hwyla, JourneyMap, Lock on, My Hero Academia, and Neat.|
Add JEI and it glitched out
Remove AP++ and or JEI and its unglitched.
Additionally Version 2 of the AP++ mod unglitches it as well. 

### Expexted Behavior

visual glitch

### Additional Context

.

### Screenshots

![image](https://user-images.githubusercontent.com/74604814/170369733-c709b147-3460-40ec-ac08-61810c97a5d1.png)
After pressing E this is what appears on screen.

**Comment by Cheos137** [comment]
can confirm, this happens with appp [1.16.5-3.0.1] + jei [1.16.5-7.7.1.152] + journeymap [1.16.5-5.8.5p2]
though that will be an annoying incompatibility to fix as journeymap crashes in the dev environment

**Comment by Cheos137** [comment]
Further testing revealed that this does only happen with journeymap versions of 5.8.0 and above

**Comment by Cheos137** [comment]
so, using journeymap 1.16.5-5.7.3 would be a workaround for the time being

**Comment by Cheos137** [comment]
Also tested this without jei - jei does not affect this issue, meaning that i only have to check one mod.. which is currently closed source... this is going to be really annoying :/

**Comment by Cheos137** [comment]
I think I've found the issue - gonna fix it now (and as 1.12 uses the same code, it's most probably affected, too)
