### ISSUE TITLE
[Bug]: 1.16.5-3.0.2 mod does not work

### ISSUE THREAD

**Issue by 6371peter** [Cheos137/ArmorpointsPlusplus#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Only add this mod,after entering the game the health bar has no change with vanilla.

### Version

3.0.2 for Minecraft Forge 1.16.5

### To Reproduce

1.Forge 1.16.5-36.2.35
2.Add armorpointspp-forge-1.16.5-3.0.2.jar
3.Create a new world

### Screenshots

![2022-06-16_18 23 03](https://user-images.githubusercontent.com/64669376/174050490-27ecb253-26e0-495d-a3e0-fb0dcc77a159.png)
when i wear any armor.
![2022-06-16_18 26 39](https://user-images.githubusercontent.com/64669376/174051068-15c625c9-3a5c-4b86-a918-08a9d44c6802.png)

**Comment by Cheos137** [comment]
In my test environment, everything is working fine - did you change any configurations?
![image](https://user-images.githubusercontent.com/54480514/174052397-d0198d59-8657-42d6-959b-0716c94efa41.png)
![image](https://user-images.githubusercontent.com/54480514/174052470-69872dc4-1e99-4c7e-ab5c-b6bd655a4a2e.png)

**Comment by 6371peter** [comment]
I try to reinstall forge 36.2.35 and only add armorpointspp-forge-1.16.5-3.0.2.jar,use java 8.0.331,config use when start game mod generate default config,but it still not working.
![2022-06-16_18 52 11](https://user-images.githubusercontent.com/64669376/174055217-78b60b5f-b42b-489e-af61-36239e17f60f.png)
General config is here:

[general]
	# Show armor value text next to armor bar
	# Available: true, false [default: true]
	showArmorValue = true
	# Show toughness bar when toughness is zero
	# Available: true, false [default: false]
	showToughnessWhenZero = false
	# Show frostbite percentage next to health bar
	# Available: true, false [default: true]
	showFrostbitePercentage = true
	# Show toughness as it's own bar
	# Available: true, false [default: false]
	useToughnessBar = false
	# Enable custom armor bar
	# Available: true, false [default: true]
	enableArmorBar = true
	# Draw shadows for all rendered texts
	# Available: true, false [default: true]
	textShadow = true
	# Enable custom health bar
	# Available: true, false [default: true]
	enableHealthBar = true
	# Show toughness as overlay over armor or it's own bar
	# Available: true, false [default: true]
	enableToughness = true
	# Frostbite heart display style (full = vanilla)
	# Available: FULL, ICON, OVERLAY [default: ICON]
	frostbiteStyle = "ICON"
	# Show absorption as border around health
	# Available: true, false [default: true]
	showAbsorption = true
	# Determines the side of the toughness bar
	# Available: RIGHT, LEFT [default: LEFT]
	# Only effective if useToughnessBar is set to true!
	toughnessSide = "LEFT"
	# Sets the texture sheet used for rendering
	# See https://github.com/Cheos137/ArmorpointsPlusplus/wiki/Custom-Texture-Sheets for more information
	# Builtin: default [default: default]
	textureSheet = "default"
	# Show resistance as border around armor
	# Available: true, false [default: true]
	showResistance = true
	# Suffix type used for displaying high numeric values
	# Available: SI, SCI, GER, ENG [default: SI]
	suffix = "SI"
	# Show protection as overlay over armor
	# Available: true, false [default: true]
	showProtection = true
	# Show health value text next to health bar
	# Available: true, false [default: true]
	showHealthValue = true
	# Show toughness value text next to toughness bar
	# Available: true, false [default: true]
	showToughnessValue = true
	# Show armor bar when armor is zero
	# Available: true, false [default: false]
	showArmorWhenZero = false

	[general.debug]
		# You don't want this to be on. Believe me
		# Available: true, false [default: false]
		debug = false

**Comment by Cheos137** [comment]
Hmmm.. that's odd.
Can you pleas send me a related log file? (ex. latest.log)

**Comment by 6371peter** [comment]
[latest.txt](https://github.com/Cheos137/ArmorpointsPlusplus/files/8918372/latest.txt)

**Comment by Cheos137** [comment]
I don't see anything wrong/weird there either...
I'm truly sorry, but i don't think i can help you there as both the config and logs indicate everything is working fine and i can't reproduce your issue on my end.

**Comment by 6371peter** [comment]
![2022-06-16_19 46 25](https://user-images.githubusercontent.com/64669376/174063150-b345f42e-0f35-48b9-9c5c-54e1e98f5992.png)
I try use armorpointspp-forge-1.16.5-3.0.1,it will working,3.0.0 and 2.0.0 also working.It seems that only 3.0.2 will happen this problem.
