### ISSUE TITLE
[Add support for 'Better Mount HUD' and 'Dehydration'] This mod interferes with other mods' hotbar elements

### ISSUE THREAD

**Issue by MScott7** [Cheos137/ArmorpointsPlusplus#32]
### Description

This mod stops mods like [Better Mount HUD](https://www.curseforge.com/minecraft/mc-mods/better-mount-hud) and [Dehydration](https://www.curseforge.com/minecraft/mc-mods/dehydration) from displaying their hotbar elements, even though they seemingly wouldn't overlap or conflict. Interestingly, it doesn't seem to interfere with [EnvironmentZ](https://www.curseforge.com/minecraft/mc-mods/environmentz)'s hotbar element.

Not marking as a bug because I don't know if this is a known side effect. Sorry if it should be marked so.

### Screenshots

Without ArmorPoints++:
![image](https://user-images.githubusercontent.com/32268672/174217414-0c62313e-8c72-4221-beb8-0f3b8d4ce033.png)
![image](https://user-images.githubusercontent.com/32268672/174217568-09afcb8d-fe17-49d2-a77d-ffc9cb568e63.png)

With ArmorPoints++:
![image](https://user-images.githubusercontent.com/32268672/174219690-3a3e0211-5b0a-4001-8ca8-2bfbc8bd8207.png)
![image](https://user-images.githubusercontent.com/32268672/174219722-76f499aa-f4ea-43d9-b3b5-96fee4d2fe78.png)

**Comment by Cheos137** [comment]
The way Armorpoints++ works on fabric is by replacing the Gui class - most mods that use mixins to inject themselves into any methods of the vanilla gui class won't work with this approach, while all mods using the fabric api event will still work.
If you want, I'll mark this as a feature request for specifically adding support for better mount hud and dehydration.

**Comment by Cheos137** [comment]
Maybe i can think of some hack to enable all mods using mixins for such to still work... we'll see.
