### ISSUE TITLE
[Feature Request]: Compatibility with Vault Hunters?

### ISSUE THREAD

**Issue by SoraNoctis** [Cheos137/ArmorpointsPlusplus#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I recently found ArmorPoints++ and I like the idea of it containing all these  modifications/additions in the hud in one mod, in the modpack I certainly find loot with various effects and high armor values, but when I tried to put the mod apparently it doesn't render or ends up being overwritten somewhere place, for some of the hud elements, I don't know how complicated it would be to add something for compatibility but i would love to see it happen and have a little more color on my hud I also installed AppleCore but I'm not sure if has something to do with it...

### Solution

Unsure about that...

### Alternatives

I tried using the separate versions that ArmorPoints++ is based on and they worked relatively well even when I had filled the screen with other mods that added character information. But I would prefer to use AP++ since for me it is more practical and I would like to continue to use it in the future in other modpacks I play. 

### Additional Context

Using the latest version of ArmorPoints++ and modpack and with these extra mods:
AppleSkin
Armor Points++
Armor Sound Tweak
FerriteCore
LazyDFU
Starlight
Smooth Boot

**Comment by Cheos137** [comment]
I'm guessing this is fabric - if not, please correct me.

Yeah, due to some internal stuff the mod does on fabric, most mods using mixins to inject into the hud renderer are incompatible (I'm looking for a solution, but don't know if I'll find any) - but yes, i can definitely add compatibility for vault hunters (or.. I'll definitely look into it)

I'll implement this with v3.1.0 which will (probably) release mid-july (so about two weeks from now, if everything goes well)

[ if this refers to forge, this is a bug, as the forge version _should_ be universally compatible ]

**Comment by SoraNoctis** [comment]
It's for the forge version of 1.16.5, I forgot to mention that ops...

**Comment by Cheos137** [comment]
oh that's weird... Then there'll be a fix for this as soon as i can get it done

**Comment by Cheos137** [comment]
Soo... i did some testing and it seems like everything works fine in my dev env but when using a normal installation nothing works at all... Once i added some debug messages and an annotation i didn't think was needed, things seem to work in the normal forge installation, too... idk what really changed

As i couldn't really get the vault hunters mod working (like... loading a world or something like that) without installing the whole modpack, i wasn't able to verify that everything works... so... do you mind testing this version: [https://files.cheos.dev/armorpointspp-forge-1.16.5-3.0.6.jar](https://files.cheos.dev/armorpointspp-forge-1.16.5-3.0.6.jar)? (don't worry, cheos.dev is my private webserver)

Uploading to curseforge and modrinth would take like... another 30mins... i'm too tired for that right now (eu time)

**Comment by SoraNoctis** [comment]
Yup it's working now super thanks!
https://imgur.com/a/0G5WqoL

**Comment by Cheos137** [comment]
Ok, I'll upload this exact jarfile to curseforge/modrinth now.
