### ISSUE TITLE
[Feature Request]: config to disable rainbow armor when at 30 points

### ISSUE THREAD

**Issue by EnderMelody** [Cheos137/ArmorpointsPlusplus#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i might have missed this but i didnt see any mention of this feature. i had to go through a lot of mods till i narrowed it down to this one, and it should probably be mentioned in the mod description. can we get a config to disable this feature as some people might not want it.

### Solution

add a config to remove the rainbow armor effect when at 30 armor points

**Comment by Cheos137** [comment]
Yea I could do that
