### ISSUE TITLE
[Bug]: health/armor/toughness text y = 0 if event gets cancelled

### ISSUE THREAD

**Issue by Cheos137** [Cheos137/ArmorpointsPlusplus#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a render event regarding the health/armor(/toughness) bar is cancelled, the corresponding text y position is never updated and thus stays at 0 forever, causing the text to render at the top of the screen.

### Version

Multiple (specify below)

### Version

3.0.x for Forge 1.12.2, Forge 1.16.5

### Expexted Behavior

the y value gets correctly set

**Comment by VuFlub** [comment]
This still hasn't been fixed...

**Comment by Cheos137** [comment]
it has. in v3.1.0 alpha versions

**Comment by Cheos137** [comment]
available on my discord
