### ISSUE TITLE
[Compatibility Request]: Spectrum Azure Dike Trinkets

### ISSUE THREAD

**Issue by Dekonker** [Cheos137/ArmorpointsPlusplus#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod name/version/id

Spectrum / Fabric 1.19+

### Link

https://www.curseforge.com/minecraft/mc-mods/spectrum

### Additional Context

Spectrum adds additional blue hearts in the form of Azure Dike trinkets. You can't see the GUI for them when using this mod and it'd be nice to be able to. The Azure Dike hearts normally sit above the armor icons. Not sure how you would want to integrate the extra hearts but I think at minimum adding like a (+ blue number) to the heart value would be enough. The attached screenshots are of before and after the mod is present which shows how the Azure Dike hearts disappear.

![2022-11-12_11 10 40_cropped](https://user-images.githubusercontent.com/6699119/201483376-457897bc-211d-4fbe-80c0-2cecff10e087.png)

![2022-11-12_11 30 48_cropped](https://user-images.githubusercontent.com/6699119/201484339-29b7c0f5-a9d9-43e4-97f5-ca0f444a9255.png)

**Comment by Cheos137** [comment]
i think i'll just add compatibility for their blue heart bar to render as usual as well as advising them to use the fabric api instead of mixins for the render hook
