### ISSUE TITLE
[Compatibility Request]: Bewitchment (Bars)

### ISSUE THREAD

**Issue by ImAK9** [Cheos137/ArmorpointsPlusplus#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Mod name/version/id

bewitchment-1.19-6

### Link

https://github.com/MoriyaShiine/bewitchment

**Comment by DaFuqs** [comment]
So, interesting heads up of a trifecta I came across receiving a bug report via bug report in the AQM2 mod pack today and to look out for when adding Witchery compat:
> AP++, Bewitchment, Spectrum

- Spectrum & Bewitchment: Dike shields render as normal (Dike shields get rendered by Spectrum)
- Spectrum & AP++: the Dike shields render as normal (Dike shields get rendered by AP++ https://github.com/Cheos137/ArmorpointsPlusplus/issues/49)
- Spectrum & AP++ & Bewitchment: Dike Shields do not get rendered (they should be rendered by AP++ https://github.com/Cheos137/ArmorpointsPlusplus/issues/49)


If I can help with anything just @ me

**Comment by Cheos137** [comment]
Did you test this with v3.1.0 alpha builds or v3.0.9, @DaFuqs ?
if it's v3.1.0 alpha, it might be worth testing with v3.0.9 (to be released when compatibility with bewitchment is confirmed - attached them here (are also somewhere in my discord))
[armorpointspp-fabric-1.18.2_1.19.2_1.19.2-3.0.9-UNZIP_ME.zip](https://github.com/Cheos137/ArmorpointsPlusplus/files/10550203/armorpointspp-fabric-1.18.2_1.19.2_1.19.2-3.0.9-UNZIP_ME.zip)

**Comment by DaFuqs** [comment]
I tested with 3.0.5, the one included in the AQM2 pack and newest one for fabric on Curseforge at this time.
Your linked dev version worked flawlessly ✔️

**Comment by Cheos137** [comment]
good to know :)
