### ISSUE TITLE
[Compatibility Request]:  Victus

### ISSUE THREAD

**Issue by MLMII** [Cheos137/ArmorpointsPlusplus#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Mod name/version/id

Victus 0.1.1.12

### Link

https://modrinth.com/mod/victus

**Comment by Cheos137** [comment]
this might take a bit... should be compatible while using the vanilla health bar with armorpoints++ (set `enableHealthBar` to false in config) for the time being

**Comment by Cheos137** [comment]
actually took less effort to implement as expected..
i can't however - due to the difference in nature of the vanilla and ap++ health bars - provide identical rendering as to when victus is used without ap++
