### ISSUE TITLE
Please reduce log spam

### ISSUE THREAD

**Issue by ChiefArug** [Cheos137/ArmorpointsPlusplus#58]
### Description

While I appreciate warning people about incompatible mods in the log, you do not need 20 lines to do so (1/3 of which do not contain text).

Something like:
```
[IncompatibleMod, IncompatibleModdy] is/are installed! These mods are known to conflict with ArmourPoints++, so you will not recieve supportt with them!
You can disable this warning in the config file, if you have sorted out the compatibility issue yourself
```
Also added in a note about the warning being able to be disabled.

**Comment by Cheos137** [comment]
there's veen an option to disable all warnings in alpha versions (currently available on my discord) for quite some time now

**Comment by ChiefArug** [comment]
I am aware of that, as I reccomended in the issue to add a note about that too.

I would still like log spam reduced regardless, 7 of those 20 lines are completely unneccassary, and as I demonstrated you can reduce the remaining 13 down to 1, plus an extra line about the config.

I would be happy to do a pull request if that would be easier.

**Comment by Cheos137** [comment]
I currently don't see the need to adjust the warning(s) and to reduce them to being less visible.
They exist for one sole purpose: to prevent idiots from complaining about incompatibilities with these specific mods.

Yes, they are verbose and could be shortened - and i did exactly what i intended when writing them.

**Comment by DaemonUmbra** [comment]
Putting my two cents in here... you could just group them all into a list so you only need to have the message once, and you could also have it all as one log entry by using newline characters.
