### ISSUE TITLE
[Compatibility Request]: Raised

### ISSUE THREAD

**Issue by slinkybass** [Cheos137/ArmorpointsPlusplus#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Mod name/version/id

Raised / fabric-1.19.3-0.14.12 / raised-fabric-1.19.3-1.1.4

### Link

https://www.curseforge.com/minecraft/mc-mods/raised

### Alternatives

Add a vertical margin to the hearts, armor and toughness bars in config

**Comment by Cheos137** [comment]
i can assure you that you are neither using the latest version available nor have checked closed issues.
