### ISSUE TITLE
[Bug]: raised compat not working

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Cheos137/ArmorpointsPlusplus#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Mod name/version/id

Raised/fabric-1.19.3-1.2.0/raised

### Link

https://github.com/yurisuika/Raised

### Additional Context

https://github.com/yurisuika/Raised/issues/30 also made an issue here

**Comment by Aces-and-Jacks** [comment]
saw you already added compatibility but it broke

**Comment by Cheos137** [comment]
fixed - won't merge this into 3.0.x, though
3.1.0 alpha build with this fix is available on my discord
