### ISSUE TITLE
Will cause the Dehydration thirst bar to disappear

### ISSUE THREAD

**Issue by wsxiya** [Cheos137/ArmorpointsPlusplus#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Description

Will cause the Dehydration thirst bar to disappear

### Version

3.0.x for Minecraft Fabric 1.19

### Version

fabric1.19.2

**Comment by Cheos137** [comment]
duplicate of #32
