### ISSUE TITLE
Installing with (raised) this mod will crash the game and won't start

### ISSUE THREAD

**Issue by wsxiya** [Cheos137/ArmorpointsPlusplus#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Mod name/version/id

fabric1.19.2+3.0.9

### Link

https://www.curseforge.com/minecraft/mc-mods/raised

**Comment by wsxiya** [comment]
Not compatible with Raised

**Comment by Cheos137** [comment]
either use raised v2.1.x or armorpoints++ v3.1.0-alpha (available on my discord)
