### ISSUE TITLE
[Bug]: broken Appleskin compatibility

### ISSUE THREAD

**Issue by grundyboy34** [Cheos137/ArmorpointsPlusplus#67]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Mod name/version/id

Appleskin-fabric1.19-2.4.1

### Link

https://www.curseforge.com/minecraft/mc-mods/appleskin

### Additional Context

When using this with appleskin, appleskin can't draw the saturation overlays unless the vanilla texture sheet is used inside armor points ++ config, but then of course armor points ++ crashes and doesn't work.

**Comment by Cheos137** [comment]
Actually, as ap++ supports appleskin - and has for quite some time now - i think you're just using the 1.19.3 version in 1.19.2, which won't work.

**Comment by grundyboy34** [comment]
As listed, I'm using the latest appleskin (2.4.1) for 1.19.2.
I was also using ap++ 1.19.2-3.0.9
For now, I just had to switch to detail armor bar

**Comment by Cheos137** [comment]
i'll look into it when i have the time to
