### ISSUE TITLE
[Feature Request]: add option to render vanilla hearts for the first 20 health

### ISSUE THREAD

**Issue by EnderMelody** [Cheos137/ArmorpointsPlusplus#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Description

currently the mod overrides any icon changes to the heart ui which prevents resource packs from changing the icons.

### Solution

 if possible, have an option that allows the first 20 hearts (the base vanilla ones) to display using the resource pack icons.

**Comment by Cheos137** [comment]
I won't start switching the used texture sheet used for rendering as this will lead both to a very convoluted code structure as well as increasing the likelihood of bugs occurring later down the line when changes to adjacent features are made.

However, resource packs *can* override the the ap++ atlas texture and you can set ap++ to solely use vanilla heart rendering if you need to.

While i won't officially support doing this, it is very probable that one can achieve what you requested with some of the features i have planned for v3.2.0
