### ISSUE TITLE
[Bug]: Crashes in survival

### ISSUE THREAD

**Issue by Omnimetatron** [Cheos137/ArmorpointsPlusplus#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Description

When a survival world is loaded, or gamemode changed from any other into survival, Minecraft crashes almost immediately.

### Version

Other (this list is not up to date - again...)

### Version

v3.1.5 [FORGE 1.20.2]

### To Reproduce

1. Be in any other gamemode
2. Change gamemode to survival
3. Crash!

### Expexted Behavior

Not to crash.

### Relevant Log / Crash-Report Output

```shell
https://gist.github.com/Omnimetatron/bed497d45b026af41dcfcc0afe21706e
```

**Comment by Cheos137** [comment]
log output shows v3.1.4 being installed which is incompatible with neoforge 20.2.59+
as it seems you intend to use v3.1.5, can you please re-check you've installed the correct version of the mod?

**Comment by Omnimetatron** [comment]
Version 3.1.5 is not listed for NeoForge on Modrinth, only Forge. As these are not compatible, I did not try that release. Check your tags...

**Comment by Omnimetatron** [comment]
3.1.5 works. I grabbed the version number from Modrinth, which is probably why I had the wrong number on my report. Thank you for bringing this to my attention, I'll be more wary in future.

**Comment by Cheos137** [comment]
oops, my bad.. should be listed correctly now
