### ISSUE TITLE
1.20.4 support

### ISSUE THREAD

**Issue by Nyphet** [Cheos137/ArmorpointsPlusplus#89]
### Description

Is a 1.20.4 version planned?

**Comment by Cheos137** [comment]
once i have time to update, yes
for neoforged: the 1.20.3 version is likely to be compatible with 1.20.4
for fabric: the 1.20.3 version might work on 1.20.4, it's worth a try

**Comment by Nyphet** [comment]
The only thing is that I need to create a modpack for a small community and I can't really publish it with metadata changed files (I think 1.20.3 is compatible with 1.20.4, but I might have to change the metadata, and anyway I can't use the official version when creating the modpack with Modrinth/CurseForge).  
Technically, nothing changes from 1.20.3 to 1.20.4, it should be just a matter of changing the build properties and releasing the new version.  
Btw, maybe I'm stupid, but I can't find the 1.20.3 Fabric version, the latest I can find is 1.20.2.

**Comment by Cheos137** [comment]
will check later today

**Comment by Cheos137** [comment]
update: neoforge 1.20.3+ is working fine, on fabric i'm currently trying to fix the modmenu config screen as some tiny change in minecraft broke it completely

**Comment by Cheos137** [comment]
merry christmas, i guess
https://modrinth.com/mod/armorpoints/version/fabric-1.20.3-3.1.5
https://modrinth.com/mod/armorpoints/version/forge-1.20.3-3.1.5

**Comment by Nyphet** [comment]
Thank you very much! Merry Christmas to you too, thanks again!
